<a id="1"></a>
# <div style="text-align:center; border-radius:15px 50px; padding:7px; color:white; margin:0; font-size:110%; font-family:Pacifico; background-color:#0f7a7a; overflow:hidden"><b>Indian Metropolitian City Rent Prediction </b></div>

* This study focuses on conducting regression analysis using Rent price in Indian top tier cities
* This study begins with simpler regression algorithms to establish a baseline, followed by boosting methods such as GradientBoosting and XGBoost. Finally, hyperparameter tuning using the OPTUNA framework will be applied to select the best-performing algorithm and if we overfit we shift to Voting/Bagging models.
* The objective is to maximize the performance metric and outline the stages of machine learning for the regression task.

#### Some Information about the dataset
##### India's housing landscape is diverse, spanning from ancient palaces to modern high-rises and rural huts. Housing growth parallels rising incomes. Renting, integral to the sharing economy, offers flexible living solutions. The dataset covers 4700+ properties with details like BHK, rent, size, floors, area type, city, furnishing, tenant preferences, bathrooms, and contact info so we try to predict its Rate using the best possible model.

##### Information about each feature:
- BHK: Number of Bedrooms, Hall, Kitchen.
- Rent: Rent of the Houses/Apartments/Flats.
- Size: Size of the Houses/Apartments/Flats in Square Feet.
- Floor: Houses/Apartments/Flats situated in which Floor and Total Number of Floors (Example: Ground out of 2, 3 out of 5, etc.)
- Area Type: Size of the Houses/Apartments/Flats calculated on either Super Area or Carpet Area or Build Area.
- Area Locality: Locality of the Houses/Apartments/Flats.
- City: City where the Houses/Apartments/Flats are Located.
- Furnishing Status: Furnishing Status of the Houses/Apartments/Flats, either it is Furnished or Semi-Furnished or Unfurnished.
- Tenant Preferred: Type of Tenant Preferred by the Owner or Agent.
- Bathroom: Number of Bathrooms.
- Point of Contact: Whom should you contact for more information regarding the Houses/Apartments/Flats.

In [2]:
import pandas as pd
df = pd.read_csv('/kaggle/input/house-rent-prediction-dataset/House_Rent_Dataset.csv')
df.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner

### Our approach strategy includes:
- Exploring each feature thoroughly.
- Assessing the correlation of each feature with the target variable.
- Performing scaling, imputation, and outlier removal as needed.
- Handling categorical features appropriately.
- Identifying patterns and relationships within the data.
- Conducting feature selection to enhance model performance.
- Evaluating various models to determine the optimal choice.
- Tuning the hyperparameters of the selected model using optimization algorithms.
- Considering ensemble methods like bagging or voting to mitigate overfitting if necessary, as they generally provide robust performance.

#### Let us look at the Dtype for each column

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4746 entries, 0 to 4745
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Posted On          4746 non-null   object
 1   BHK                4746 non-null   int64
 2   Rent               4746 non-null   int64
 3   Size               4746 non-null   int64
 4   Floor              4746 non-null   object
 5   Area Type          4746 non-null   object
 6   Area Locality      4746 non-null   object
 7   City               4746 non-null   object
 8   Furnishing Status  4746 non-null   object
 9   Tenant Preferred   4746 non-null   object
 10  Bathroom           4746 non-null   int64
 11  Point of Contact   4746 non-null   object
dtypes: int64(4), object(8)
memory usage: 445.1+ KB

In [4]:
print(f'DataFrame size: {df.shape}')

DataFrame size: (4746, 12)

#### The below code is just to seperate Current floor and Total Floor, because by intuition we know that in India most of flats are cheaper in lower floors so It will be useful later on and also it is object Data type so anyways we need to convert it to numerical column lol

In [5]:
# Regular expression to extract the current floor and total number of floors
pattern = r'(?P<CurrentFloor>\w+)\s*out\s*of\s*(?P<TotalFloors>\d+)'

# Extract the values into new columns
df[['CurrentFloor', 'TotalFloors']] = df['Floor'].str.extract(pattern)

# Replace non-numeric floor labels with specific values
floor_replacements = {
    'Ground': 0,
    'Basement': -1  # Assuming 'Basement' should be treated as floor -1
}

df['CurrentFloor'] = df['CurrentFloor'].replace(floor_replacements)

# Convert columns to appropriate data types
df['CurrentFloor'] = pd.to_numeric(df['CurrentFloor'], errors='coerce')
df['TotalFloors'] = pd.to_numeric(df['TotalFloors'], errors='coerce')
df = df.drop(columns=['Floor'])
df.head()

,Posted On,BHK,Rent,Size,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact,CurrentFloor,TotalFloors
0,2022-05-18,2,10000,1100,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner,0.0,2.0
1,2022-05-13,2,20000,800,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner,1.0,3.0
2,2022-05-16,2,17000,1000,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner,1.0,3.0
3,2022-07-04,2,10000,800,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner,1.0,2.0
4,2022-05-09,2,7500,850,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner,1.0,2.0

#### Now we will check the number of categorical feature with number of unique value

In [6]:
categorical_columns = df.select_dtypes(include=['object']).columns
unique_counts = df[categorical_columns].nunique()
print(unique_counts)

Posted On              81
Area Type               3
Area Locality        2235
City                    6
Furnishing Status       3
Tenant Preferred        3
Point of Contact        3
dtype: int64

#### Observation: Out of 4746 columns we have 2235 which is nearabout 50% so I dont think Area Type column will contribute much to our model due to High Cardinality but anyways we will get feature importance through various techniques later on

In [7]:
print(f'Number of missing values in DataFrame:\n{df.isna().sum()}')

Number of missing values in DataFrame:
Posted On            0
BHK                  0
Rent                 0
Size                 0
Area Type            0
Area Locality        0
City                 0
Furnishing Status    0
Tenant Preferred     0
Bathroom             0
Point of Contact     0
CurrentFloor         4
TotalFloors          4
dtype: int64

In [8]:
# We will use KNN Imputer to fill these missing values, Though we can drop it too but anyways even if we get it as outlier we can remove it later on
from sklearn.impute import KNNImputer
columns_for_imputation = ['CurrentFloor', 'TotalFloors']
imputer = KNNImputer(n_neighbors=3)
df[columns_for_imputation] = imputer.fit_transform(df[columns_for_imputation])

In [9]:
print(f'Number of missing values in DataFrame:\n{df.isna().sum()}')

Number of missing values in DataFrame:
Posted On            0
BHK                  0
Rent                 0
Size                 0
Area Type            0
Area Locality        0
City                 0
Furnishing Status    0
Tenant Preferred     0
Bathroom             0
Point of Contact     0
CurrentFloor         0
TotalFloors          0
dtype: int64

#### We will seperate out the Year from Posted On column because price increases in a year due to inflation or any reason so finding out pattern day or month wise is difficult

In [10]:
df['Year'] = pd.to_datetime(df['Posted On']).dt.year
df = df.drop(columns=['Posted On'])
df.head()

,BHK,Rent,Size,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact,CurrentFloor,TotalFloors,Year
0,2,10000,1100,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner,0.0,2.0,2022
1,2,20000,800,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner,1.0,3.0,2022
2,2,17000,1000,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner,1.0,3.0,2022
3,2,10000,800,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner,1.0,2.0,2022
4,2,7500,850,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner,1.0,2.0,2022

In [11]:
value_counts = df['City'].value_counts()
print(value_counts)

City
Mumbai       972
Chennai      891
Bangalore    886
Hyderabad    868
Delhi        605
Kolkata      524
Name: count, dtype: int64

#### Observation: Almost equally distributed so it is balanced which is actually desired

<a id="1"></a> 
# <div style="text-align:center; border-radius:15px 50px; padding:7px; color:white; margin:0; font-size:110%; font-family:Pacifico; background-color:#0f7a7a; overflow:hidden"><b>Sneak Peek into the data 👀 </b></div>

#### Inporting all Important Libraries we gonna use

In [12]:
import numpy as np  
import pandas as pd  
import matplotlib.pyplot as plt  
import seaborn as sns  
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import optuna
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from xgboost import XGBRegressor
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')  # ignore notifications
import sys
import os

#### Finding out some basic pattern using sunburst,the sunburst chart below visually represents the distribution of flats based on various attributes: City, Area Type, Furnishing Status, and Tenant Preferred. It provides an intuitive way to explore how different combinations of these factors contribute to the overall allocation of flats, highlighting patterns and relationships within the dataset.

In [13]:
fig = px.sunburst(
    df, 
    path=['City', 'Area Type', 'Furnishing Status', 'Tenant Preferred'], 
    width=700,
    height=700,
    title='Allotment of flats according to Bachelors/Family/(Bachelors/Family)',
    color_discrete_sequence=px.colors.cyclical.Phase
)

fig.show()

<a id="1"></a> 
# <div style="text-align:center; border-radius:15px 50px; padding:7px; color:white; margin:0; font-size:110%; font-family:Pacifico; background-color:#0f7a7a; overflow:hidden"><b>Sneak Peek into Boxplot 👀 </b></div>

In [55]:
scl = [ [0,"rgb(5, 10, 172)"],[0.35,"rgb(40, 60, 190)"],[0.5,"rgb(70, 100, 245)"],\
    [0.6,"rgb(90, 120, 245)"],[0.7,"rgb(106, 137, 247)"],[1,"rgb(220, 220, 220)"] ]
fig = px.box(df, x="Furnishing Status", y="Rent", template='plotly_dark', title='<b>Boxplots', color='Furnishing Status')
fig.update_layout(title_x=0.5)
fig.show()

#### Observation: Unfurnished houses for rent are having less rent as compared to others.

In [56]:
scl = [ [0,"rgb(5, 10, 172)"],[0.35,"rgb(40, 60, 190)"],[0.5,"rgb(70, 100, 245)"],\
    [0.6,"rgb(90, 120, 245)"],[0.7,"rgb(106, 137, 247)"],[1,"rgb(220, 220, 220)"] ]
fig = px.box(df, x="Point of Contact", y="Rent", template='plotly_dark', title='<b>Boxplots', color='Point of Contact')
fig.update_layout(title_x=0.5)
fig.show()

#### Observations: The higher rent for properties obtained through a contact agent may reflect additional costs to compensate the agent's services. In contrast, renting directly from builders tends to be less expensive.

In [ ]:
scl = [ [0,"rgb(5, 10, 172)"],[0.35,"rgb(40, 60, 190)"],[0.5,"rgb(70, 100, 245)"],\
    [0.6,"rgb(90, 120, 245)"],[0.7,"rgb(106, 137, 247)"],[1,"rgb(220, 220, 220)"] ]
fig = px.box(df, x="Tenant Preferred", y="Rent", template='plotly_dark', title='<b>Boxplots', color='Tenant Preferred')
fig.update_layout(title_x=0.5)
fig.show()

#### Objservation: Houses rented with no tenant conditions are having a bit more rent as compared to others.

In [ ]:
scl = [ [0,"rgb(5, 10, 172)"],[0.35,"rgb(40, 60, 190)"],[0.5,"rgb(70, 100, 245)"],\
    [0.6,"rgb(90, 120, 245)"],[0.7,"rgb(106, 137, 247)"],[1,"rgb(220, 220, 220)"] ]
fig = px.box(df, x="City", y="Rent", template='plotly_dark', title='<b>Boxplots', color='City')
fig.update_layout(title_x=0.5)
fig.show()

#### Observations: Mumbai has a high demand for housing, leading to higher rents, likely due to the high influx of job seekers and corporate relocations. Other cities, except Kolkata, have relatively equal rent levels. Kolkata has lower rents, which can be attributed to its comparatively less developed job sectors and lifestyle, resulting in lower demand for rental properties.

<a id="1"></a> 
# <div style="text-align:center; border-radius:15px 50px; padding:7px; color:white; margin:0; font-size:110%; font-family:Pacifico; background-color:#0f7a7a; overflow:hidden"><b>Sneak Peek into each feature one by one 👀 </b></div>

In [ ]:
import plotly.express as px
grouped_df = df.groupby('City', as_index=False)['Rent'].mean()
sorted_df = grouped_df.sort_values(by='Rent', ascending=False)

fig = px.bar(sorted_df, x='City', y='Rent', color_discrete_sequence=['steelblue'], template='plotly_dark', title='<b> Average Rent by City </b>')
fig.update_layout(title_x=0.5)
fig.show()

#### Observation: As observed before Housess in mumbai have relatively high prices for so and so reason

In [ ]:
import plotly.express as px
grouped_df = df.groupby('Furnishing Status', as_index=False)['Rent'].mean()
sorted_df = grouped_df.sort_values(by='Rent', ascending=False)

fig = px.bar(sorted_df, x='Furnishing Status', y='Rent', color_discrete_sequence=['steelblue'], template='plotly_dark', title='<b> Average Rent by Furnishing Status </b>')
fig.update_layout(title_x=0.5)
fig.show()

In [ ]:
import plotly.express as px
grouped_df = df.groupby('BHK', as_index=False)['Rent'].mean()
sorted_df = grouped_df.sort_values(by='Rent', ascending=False)

fig = px.bar(sorted_df, x='BHK', y='Rent', color_discrete_sequence=['steelblue'], template='plotly_dark', title='<b> Average Rent by Furnishing Status </b>')
fig.update_layout(title_x=0.5)
fig.show()

#### Observation: Rent prices of houses tend to increase with the number of bedrooms (BHK). This trend reflects larger properties commanding higher rents due to their increased space and amenities. Conversely, 6 BHK properties are less sought after, resulting in lower rental prices due to lower demand (Reason Unknown lol)

In [ ]:
fig = make_subplots(rows=1, cols=2, subplot_titles=('<i>Rent', '<i>Size'))
fig.add_trace(go.Histogram(x=df['Rent'], name='Rent'), row=1, col=1)
fig.add_trace(go.Histogram(x=df['Size'], name='Size'), row=1, col=2)
fig.update_layout(template='plotly_dark', title_text='<b>Distributions', title_x=0.5)

<a id="1"></a> 
# <div style="text-align:center; border-radius:15px 50px; padding:7px; color:white; margin:0; font-size:110%; font-family:Pacifico; background-color:#0f7a7a; overflow:hidden"><b>Linear dependency on Size and Rent </b></div>

In [ ]:
fig = px.scatter(df, x="Size", y="Rent", trendline="ols", color_discrete_sequence=['steelbl'],
                template='plotly_dark', title='<b>Target variable dependency on median_income', color='Rent', color_continuous_scale=px.colors.sequential.Blues)
fig.update_layout(title_x=0.5)
fig.show()

In [ ]:
fig = px.scatter(
    df,
    x='Rent',
    y='Size',
    color='Size',
    size='Size',
    color_continuous_scale='viridis',
    title='Scatter plot of Rent vs Size',
    labels={'Rent': 'Rent Amount', 'Size': 'Size of the Apartment'},
    template='plotly_dark'
)

fig.update_layout(
    title_x=0.5,
    width=800,
    height=400
)
fig.show()

In [ ]:
categorical_columns = df.select_dtypes(include=['object']).columns
unique_counts = df[categorical_columns].nunique()
print(unique_counts)

Area Type               3
Area Locality        2235
City                    6
Furnishing Status       3
Tenant Preferred        3
Point of Contact        3
dtype: int64

<a id="1"></a> 
# <div style="text-align:center; border-radius:15px 50px; padding:7px; color:white; margin:0; font-size:110%; font-family:Pacifico; background-color:#0f7a7a; overflow:hidden"><b>Converting Categorical to numerical using LabelEncoder </b></div>

In [14]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Area Type'] = label_encoder.fit_transform(df['Area Type'])
df['Area Locality'] = label_encoder.fit_transform(df['Area Locality'])
df['City'] = label_encoder.fit_transform(df['City'])
df['Furnishing Status'] = label_encoder.fit_transform(df['Furnishing Status'])
df['Tenant Preferred'] = label_encoder.fit_transform(df['Tenant Preferred'])
df['Point of Contact'] = label_encoder.fit_transform(df['Point of Contact'])

df.head()

,BHK,Rent,Size,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact,CurrentFloor,TotalFloors,Year
0,2,10000,1100,2,221,4,2,1,2,2,0.0,2.0,2022
1,2,20000,800,2,1527,4,1,1,1,2,1.0,3.0,2022
2,2,17000,1000,2,1760,4,1,1,1,2,1.0,3.0,2022
3,2,10000,800,2,526,4,2,1,1,2,1.0,2.0,2022
4,2,7500,850,1,1890,4,2,0,1,2,1.0,2.0,2022

<a id="1"></a> 
# <div style="text-align:center; border-radius:15px 50px; padding:7px; color:white; margin:0; font-size:110%; font-family:Pacifico; background-color:#0f7a7a; overflow:hidden"><b>Feature correlation and Feature selection </b></div>

In [15]:
df.corr()['Rent']

BHK                  0.369718
Rent                 1.000000
Size                 0.413551
Area Type           -0.214867
Area Locality       -0.018849
City                 0.210525
Furnishing Status   -0.146251
Tenant Preferred     0.006027
Bathroom             0.441215
Point of Contact    -0.339677
CurrentFloor         0.326358
TotalFloors          0.352205
Year                      NaN
Name: Rent, dtype: float64

#### We can see already that Area type is the least dependent upon target variable (Rent)

In [68]:
fig=px.imshow(df.corr(),text_auto=True, template='plotly_dark', color_continuous_scale=px.colors.sequential.Blues, aspect='auto',title='<b>Correlation matrix')
fig.update_layout(title_x=0.5)
fig.show()

In [16]:
df.corr()['Area Type']

BHK                 -0.153225
Rent                -0.214867
Size                -0.079705
Area Type            1.000000
Area Locality       -0.007743
City                -0.282856
Furnishing Status    0.056276
Tenant Preferred     0.155388
Bathroom            -0.183012
Point of Contact     0.559451
CurrentFloor        -0.254626
TotalFloors         -0.285407
Year                      NaN
Name: Area Type, dtype: float64

In [17]:
value_counts = df['Year'].value_counts()
print(value_counts)

Year
2022    4746
Name: count, dtype: int64

#### Ah we did useless hardwork before as in this dataset we just have datas of 2022 lmao so let us just drop it

In [18]:
columns_to_drop = ['Year']
df = df.drop(columns=columns_to_drop)
df.head()

,BHK,Rent,Size,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact,CurrentFloor,TotalFloors
0,2,10000,1100,2,221,4,2,1,2,2,0.0,2.0
1,2,20000,800,2,1527,4,1,1,1,2,1.0,3.0
2,2,17000,1000,2,1760,4,1,1,1,2,1.0,3.0
3,2,10000,800,2,526,4,2,1,1,2,1.0,2.0
4,2,7500,850,1,1890,4,2,0,1,2,1.0,2.0

In [19]:
# Removing Outliers
Q1 = df['Rent'].quantile(0.25)
Q3 = df['Rent'].quantile(0.75)
IQR = Q3 - Q1
df = df[~((df['Rent'] < (Q1 - 1.5 * IQR)) | (df['Rent'] > (Q3 + 1.5 * IQR)))]
df

,BHK,Rent,Size,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact,CurrentFloor,TotalFloors
0,2,10000,1100,2,221,4,2,1,2,2,0.0,2.0
1,2,20000,800,2,1527,4,1,1,1,2,1.0,3.0
2,2,17000,1000,2,1760,4,1,1,1,2,1.0,3.0
3,2,10000,800,2,526,4,2,1,1,2,1.0,2.0
4,2,7500,850,1,1890,4,2,0,1,2,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2,15000,1000,1,219,3,1,1,2,2,3.0,5.0
4742,3,29000,2000,2,1214,3,1,1,3,2,1.0,4.0
4743,3,35000,1750,1,724,3,1,1,3,0,3.0,5.0
4744,3,45000,1500,1,590,3,1,2,2,0,23.0,34.0
4745,2,15000,1000,1,1915,3,2,0,2,2,4.0,5.0

<a id="1"></a> 
# <div style="text-align:center; border-radius:15px 50px; padding:7px; color:white; margin:0; font-size:110%; font-family:Pacifico; background-color:#0f7a7a; overflow:hidden"><b>Train Test Split </b></div>

In [20]:
y = df['Rent']
X = df.drop(columns=['Rent'])
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, shuffle=True, test_size=0.3)

In [21]:
print(f'X_train size: {X_train.shape}')

X_train size: (2958, 11)

<a id="1"></a> 
# <div style="text-align:center; border-radius:15px 50px; padding:7px; color:white; margin:0; font-size:110%; font-family:Pacifico; background-color:#0f7a7a; overflow:hidden"><b>Scaling the data </b></div>

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train_scaled= pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled= pd.DataFrame(X_test_scaled, columns=X_test.columns)
X_train.head()

,BHK,Size,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact,CurrentFloor,TotalFloors
177,2,600,1,1404,4,2,1,1,2,1.0,2.0
423,2,550,1,1762,4,2,1,1,0,2.0,3.0
2002,2,800,2,1324,0,0,1,2,2,2.0,3.0
4093,3,1675,2,590,3,2,1,3,2,5.0,12.0
2650,1,400,1,1207,2,2,0,1,2,2.0,4.0

In [23]:
X_train_scaled.head()

,BHK,Size,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact,CurrentFloor,TotalFloors
0,0.056772,-0.560958,-1.143388,0.470287,1.023278,1.096230,0.151256,-1.147986,0.571755,-0.435039,-0.552052
1,0.056772,-0.664961,-1.143388,1.036290,1.023278,1.096230,0.151256,-1.147986,-1.749798,-0.156554,-0.388721
2,0.056772,-0.144943,0.872191,0.343806,-1.329049,-1.889634,0.151256,0.278797,0.571755,-0.156554,-0.388721
3,1.411052,1.675122,0.872191,-0.816657,0.435196,1.096230,0.151256,1.705579,0.571755,0.678900,1.081253
4,-1.297509,-0.976972,-1.143388,0.158828,-0.152885,1.096230,-1.828458,-1.147986,0.571755,-0.156554,-0.225391

<a id="1"></a> 
# <div style="text-align:center; border-radius:15px 50px; padding:7px; color:white; margin:0; font-size:110%; font-family:Pacifico; background-color:#0f7a7a; overflow:hidden"><b>Feature Important using Random forest to cross validate </b></div>

In [77]:
# Let's look at the feature importance:
rf = RandomForestRegressor()
rf.fit(X_train, y_train)
fig = go.Figure(go.Bar(
            x=rf.feature_importances_,
            y=X_train.columns,
            orientation='h', marker_color='steelblue'))
fig.update_layout(template='plotly_dark', title='<b>Estimating feature importance through the Random Forest model', title_x=0.5, 
                 xaxis_title="Feature importance", yaxis_title='Feature')

fig.show()

#### Observation: As predicted before Area Type is the least important so let us simply drop it

In [24]:
columns_to_drop = ['Area Type']
X_train = X_train.drop(columns=columns_to_drop)
X_train_scaled = X_train_scaled.drop(columns=columns_to_drop)
X_test = X_test.drop(columns=columns_to_drop)
X_test_scaled = X_test_scaled.drop(columns=columns_to_drop)
#X_test_scaled

<a id="1"></a> 
# <div style="text-align:center; border-radius:15px 50px; padding:7px; color:white; margin:0; font-size:110%; font-family:Pacifico; background-color:#0f7a7a; overflow:hidden"><b>Model selection: Trying out different Regression models on default hyperparameters </b></div>

In [79]:
import lightgbm as lgb
from catboost import CatBoostRegressor
df_models = pd.DataFrame(data=None, columns=['Algorithm', 'r2_train', 'r2_test'])

def make_model(X_tr, X_te, y_tr, y_te, model, model_name: str): 
    model.fit(X_tr, y_tr)
    y_pred_train = model.predict(X_tr)
    y_pred_test = model.predict(X_te)
    r2_train = r2_score(y_tr, y_pred_train)
    r2_test = r2_score(y_te, y_pred_test)
    df_models.loc[len(df_models.index)] = [model_name, r2_train, r2_test]
                       

make_model(X_train_scaled, X_test_scaled, y_train, y_test, LinearRegression(), 'LinearRegression')
make_model(X_train_scaled, X_test_scaled, y_train, y_test, Ridge(), 'Ridge')
make_model(X_train_scaled, X_test_scaled, y_train, y_test, Lasso(), 'Lasso')
make_model(X_train_scaled, X_test_scaled, y_train, y_test, ElasticNet(), 'ElasticNet')
make_model(X_train, X_test, y_train, y_test, GradientBoostingRegressor(), 'GradientBoosting')
make_model(X_train, X_test, y_train, y_test, RandomForestRegressor(), 'RandomForest')
make_model(X_train, X_test, y_train, y_test, XGBRegressor(), 'XGBoost')
make_model(X_train, X_test, y_train, y_test, lgb.LGBMRegressor(), 'LightGBM')
make_model(X_train, X_test, y_train, y_test, CatBoostRegressor(), 'CatBoost')

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000995 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 586
[LightGBM] [Info] Number of data points in the train set: 2958, number of used features: 10
[LightGBM] [Info] Start training from score 19244.111562
Learning rate set to 0.048596
0:	learn: 13250.2007679	total: 1.69ms	remaining: 1.69s
1:	learn: 12859.7365992	total: 3.27ms	remaining: 1.63s
2:	learn: 12492.9439272	total: 4.74ms	remaining: 1.57s
3:	learn: 12159.3315760	total: 5.98ms	remaining: 1.49s
4:	learn: 11842.6200999	total: 7.4ms	remaining: 1.47s
5:	learn: 11555.3664108	total: 8.89ms	remaining: 1.47s
6:	learn: 11262.0032765	total: 10.2ms	remaining: 1.45s
7:	learn: 11008.3647306	total: 11.6ms	remaining: 1.44s
8:	learn: 10789.1448878	total: 12.9ms	remaining: 1.42s
9:	learn: 10574.3995605	total: 14.3ms	remaining: 1.42s
10:	learn: 10377.1924489	total: 15.7ms	remaining: 1.42s
11:	learn: 10164.9384124	total: 17.1ms	remaining: 1.41s
12:	learn: 9962.7622530	total: 18.6ms	remaining: 1.41s
13:	learn: 9764.4509646	total: 19.9ms	remaining: 1.41s
14:	learn: 9592.2427315	total: 21.3ms	remaining: 1.4s
15:	learn: 9426.8127618	total: 23ms	remaining: 1.41s
16:	learn: 9273.0832573	total: 24.4ms	remaining: 1.41s
17:	learn: 9130.6534367	total: 25.7ms	remaining: 1.4s
18:	learn: 8995.5803060	total: 27ms	remaining: 1.39s
19:	learn: 8881.6069120	total: 28.8ms	remaining: 1.41s
20:	learn: 8764.2240691	total: 30.3ms	remaining: 1.41s
21:	learn: 8652.4577083	total: 31.7ms	remaining: 1.41s
22:	learn: 8546.6804689	total: 33.1ms	remaining: 1.41s
23:	learn: 8432.4138453	total: 34.6ms	remaining: 1.41s
24:	learn: 8327.4371033	total: 36ms	remaining: 1.4s
25:	learn: 8244.5585600	total: 37.5ms	remaining: 1.41s
26:	learn: 8160.5246879	total: 39ms	remaining: 1.4s
27:	learn: 8082.5167021	total: 40.2ms	remaining: 1.4s
28:	learn: 8012.5687621	total: 41.5ms	remaining: 1.39s
29:	learn: 7940.2062526	total: 42.9ms	remaining: 1.39s
30:	learn: 7874.6592069	total: 44.4ms	remaining: 1.39s
31:	learn: 7819.6692416	total: 45.8ms	remaining: 1.39s
32:	learn: 7768.3006223	total: 47.3ms	remaining: 1.39s
33:	learn: 7715.7044520	total: 48.8ms	remaining: 1.39s
34:	learn: 7657.0905436	total: 50.3ms	remaining: 1.39s
35:	learn: 7606.2848592	total: 51.8ms	remaining: 1.39s
36:	learn: 7563.1444918	total: 53.2ms	remaining: 1.38s
37:	learn: 7524.1002510	total: 55.4ms	remaining: 1.4s
38:	learn: 7482.9490991	total: 57ms	remaining: 1.41s
39:	learn: 7444.3474355	total: 59.2ms	remaining: 1.42s
40:	learn: 7400.6501800	total: 60.8ms	remaining: 1.42s
41:	learn: 7367.3569439	total: 62.1ms	remaining: 1.42s
42:	learn: 7338.4642960	total: 63.8ms	remaining: 1.42s
43:	learn: 7311.0878098	total: 65.6ms	remaining: 1.42s
44:	learn: 7283.5866731	total: 67ms	remaining: 1.42s
45:	learn: 7253.7596772	total: 68.5ms	remaining: 1.42s
46:	learn: 7220.1859883	total: 69.8ms	remaining: 1.42s
47:	learn: 7190.9756560	total: 71.3ms	remaining: 1.41s
48:	learn: 7166.0928651	total: 73.1ms	remaining: 1.42s
49:	learn: 7139.5773877	total: 74.4ms	remaining: 1.41s
50:	learn: 7113.0242763	total: 75.9ms	remaining: 1.41s
51:	learn: 7085.6046288	total: 77.6ms	remaining: 1.41s
52:	learn: 7067.4764113	total: 79ms	remaining: 1.41s
53:	learn: 7046.6548322	total: 80.4ms	remaining: 1.41s
54:	learn: 7026.8293896	total: 82ms	remaining: 1.41s
55:	learn: 7009.1079534	total: 83.6ms	remaining: 1.41s
56:	learn: 6989.7035251	total: 85.6ms	remaining: 1.42s
57:	learn: 6966.8727544	total: 87.7ms	remaining: 1.42s
58:	learn: 6950.1634344	total: 89.1ms	remaining: 1.42s
59:	learn: 6935.2170482	total: 91ms	remaining: 1.43s
60:	learn: 6916.6641146	total: 93.4ms	remaining: 1.44s
61:	learn: 6903.6676669	total: 95.3ms	remaining: 1.44s
62:	learn: 6888.4094747	total: 96.7ms	remaining: 1.44s
63:	learn: 6871.7487930	total: 98.8ms	remaining: 1.45s
64:	learn: 6856.5849590	total: 102ms	remaining: 1.46s
65:	learn: 6844.0350031	total: 103ms	remaining: 1.46s
66:	learn: 6832.8962395	total: 105ms	remaining: 1.46s
67:	learn: 6817.4052444	total: 106ms	remaining: 1.46s
68:	learn: 6802.0975968	total: 108ms	remaining: 1.46s
69:	learn: 6792.8541000	total: 110ms	remaining: 1.47s
70:	learn: 6778.8501098	total: 112ms	remaining: 1.47s
71:	learn: 6770.5222298	total: 114ms	remaining: 1.47s
72:	learn: 6756.9864924	total: 117ms	remaining: 1.48s
73:	learn: 6745.3673090	total: 118ms	remaining: 1.48s
74:	learn: 6735.7990130	total: 120ms	remaining: 1.48s
75:	learn: 6723.7148658	total: 122ms	remaining: 1.49s
76:	learn: 6712.2837365	total: 124ms	remaining: 1.49s
77:	learn: 6703.5411331	total: 126ms	remaining: 1.49s
78:	learn: 6692.0993604	total: 127ms	remaining: 1.49s
79:	learn: 6681.4529787	total: 129ms	remaining: 1.49s
80:	learn: 6673.6423078	total: 131ms	remaining: 1.48s
81:	learn: 6663.1911484	total: 132ms	remaining: 1.48s
82:	learn: 6653.7345863	total: 134ms	remaining: 1.48s
83:	learn: 6645.0964853	total: 135ms	remaining: 1.48s
84:	learn: 6636.9805972	total: 137ms	remaining: 1.48s
85:	learn: 6629.9248687	total: 139ms	remaining: 1.47s
86:	learn: 6621.3727306	total: 140ms	remaining: 1.47s
87:	learn: 6613.0972222	total: 142ms	remaining: 1.47s
88:	learn: 6608.7180247	total: 143ms	remaining: 1.47s
89:	learn: 6596.1186134	total: 145ms	remaining: 1.46s
90:	learn: 6587.7616915	total: 146ms	remaining: 1.46s
91:	learn: 6581.3315399	total: 148ms	remaining: 1.46s
92:	learn: 6576.5690924	total: 149ms	remaining: 1.46s
93:	learn: 6567.8719681	total: 151ms	remaining: 1.45s
94:	learn: 6561.7037572	total: 152ms	remaining: 1.45s
95:	learn: 6556.4984017	total: 154ms	remaining: 1.45s
96:	learn: 6544.3287770	total: 156ms	remaining: 1.45s
97:	learn: 6537.9892996	total: 157ms	remaining: 1.45s
98:	learn: 6532.5199179	total: 159ms	remaining: 1.44s
99:	learn: 6523.3213326	total: 160ms	remaining: 1.44s
100:	learn: 6517.8195246	total: 161ms	remaining: 1.44s
101:	learn: 6508.2969736	total: 163ms	remaining: 1.43s
102:	learn: 6502.6412137	total: 164ms	remaining: 1.43s
103:	learn: 6498.3809013	total: 166ms	remaining: 1.43s
104:	learn: 6492.8187491	total: 167ms	remaining: 1.42s
105:	learn: 6487.1378317	total: 168ms	remaining: 1.42s
106:	learn: 6480.1623131	total: 170ms	remaining: 1.42s
107:	learn: 6473.5588455	total: 171ms	remaining: 1.41s
108:	learn: 6467.3126994	total: 173ms	remaining: 1.41s
109:	learn: 6463.1713456	total: 174ms	remaining: 1.41s
110:	learn: 6457.6846968	total: 175ms	remaining: 1.4s
111:	learn: 6452.0568906	total: 177ms	remaining: 1.4s
112:	learn: 6446.8567835	total: 179ms	remaining: 1.4s
113:	learn: 6437.9101711	total: 180ms	remaining: 1.4s
114:	learn: 6432.5757962	total: 182ms	remaining: 1.4s
115:	learn: 6426.3044706	total: 184ms	remaining: 1.4s
116:	learn: 6418.6308314	total: 185ms	remaining: 1.4s
117:	learn: 6412.7722631	total: 187ms	remaining: 1.4s
118:	learn: 6409.4885536	total: 188ms	remaining: 1.4s
119:	learn: 6402.4175658	total: 190ms	remaining: 1.39s
120:	learn: 6397.8080114	total: 192ms	remaining: 1.39s
121:	learn: 6391.1309497	total: 193ms	remaining: 1.39s
122:	learn: 6387.6376483	total: 195ms	remaining: 1.39s
123:	learn: 6381.6040350	total: 196ms	remaining: 1.39s
124:	learn: 6378.8077413	total: 198ms	remaining: 1.39s
125:	learn: 6369.5347691	total: 200ms	remaining: 1.39s
126:	learn: 6363.9521119	total: 202ms	remaining: 1.39s
127:	learn: 6361.7586282	total: 203ms	remaining: 1.38s
128:	learn: 6352.2674410	total: 205ms	remaining: 1.38s
129:	learn: 6345.9444998	total: 206ms	remaining: 1.38s
130:	learn: 6343.0081051	total: 207ms	remaining: 1.38s
131:	learn: 6339.0659351	total: 209ms	remaining: 1.37s
132:	learn: 6335.2313846	total: 210ms	remaining: 1.37s
133:	learn: 6327.0962636	total: 212ms	remaining: 1.37s
134:	learn: 6317.0865858	total: 213ms	remaining: 1.36s
135:	learn: 6314.9306781	total: 215ms	remaining: 1.36s
136:	learn: 6312.4582521	total: 216ms	remaining: 1.36s
137:	learn: 6306.7635218	total: 217ms	remaining: 1.36s
138:	learn: 6301.2380210	total: 219ms	remaining: 1.35s
139:	learn: 6296.4775360	total: 220ms	remaining: 1.35s
140:	learn: 6292.2093038	total: 221ms	remaining: 1.35s
141:	learn: 6288.6562369	total: 223ms	remaining: 1.35s
142:	learn: 6283.4154668	total: 225ms	remaining: 1.34s
143:	learn: 6274.9043488	total: 226ms	remaining: 1.34s
144:	learn: 6270.4447942	total: 227ms	remaining: 1.34s
145:	learn: 6264.7890444	total: 229ms	remaining: 1.34s
146:	learn: 6257.2430195	total: 230ms	remaining: 1.33s
147:	learn: 6251.5971180	total: 232ms	remaining: 1.34s
148:	learn: 6244.8696597	total: 234ms	remaining: 1.34s
149:	learn: 6240.3184376	total: 236ms	remaining: 1.33s
150:	learn: 6235.4580837	total: 237ms	remaining: 1.33s
151:	learn: 6229.6842056	total: 240ms	remaining: 1.34s
152:	learn: 6224.2976100	total: 241ms	remaining: 1.33s
153:	learn: 6218.1787132	total: 243ms	remaining: 1.34s
154:	learn: 6213.9123897	total: 245ms	remaining: 1.34s
155:	learn: 6206.0891384	total: 247ms	remaining: 1.33s
156:	learn: 6203.7731263	total: 248ms	remaining: 1.33s
157:	learn: 6200.4931806	total: 249ms	remaining: 1.33s
158:	learn: 6193.4441203	total: 251ms	remaining: 1.33s
159:	learn: 6189.7021292	total: 252ms	remaining: 1.32s
160:	learn: 6180.1202641	total: 254ms	remaining: 1.32s
161:	learn: 6173.3895822	total: 255ms	remaining: 1.32s
162:	learn: 6167.7635332	total: 256ms	remaining: 1.32s
163:	learn: 6158.1190786	total: 258ms	remaining: 1.31s
164:	learn: 6153.3324973	total: 259ms	remaining: 1.31s
165:	learn: 6150.9425937	total: 260ms	remaining: 1.31s
166:	learn: 6146.2896196	total: 262ms	remaining: 1.3s
167:	learn: 6142.1326807	total: 263ms	remaining: 1.3s
168:	learn: 6136.1207845	total: 265ms	remaining: 1.3s
169:	learn: 6131.3373362	total: 266ms	remaining: 1.3s
170:	learn: 6126.4243150	total: 267ms	remaining: 1.3s
171:	learn: 6120.7453558	total: 269ms	remaining: 1.29s
172:	learn: 6117.8569176	total: 270ms	remaining: 1.29s
173:	learn: 6113.2312653	total: 272ms	remaining: 1.29s
174:	learn: 6109.6164654	total: 273ms	remaining: 1.29s
175:	learn: 6104.2643264	total: 274ms	remaining: 1.28s
176:	learn: 6097.1432924	total: 276ms	remaining: 1.28s
177:	learn: 6092.0048895	total: 277ms	remaining: 1.28s
178:	learn: 6085.9675155	total: 279ms	remaining: 1.28s
179:	learn: 6080.5977823	total: 280ms	remaining: 1.27s
180:	learn: 6076.0668090	total: 281ms	remaining: 1.27s
181:	learn: 6073.1145697	total: 283ms	remaining: 1.27s
182:	learn: 6070.9537786	total: 284ms	remaining: 1.27s
183:	learn: 6068.4176556	total: 286ms	remaining: 1.27s
184:	learn: 6064.4644953	total: 287ms	remaining: 1.26s
185:	learn: 6061.4496561	total: 288ms	remaining: 1.26s
186:	learn: 6056.9888245	total: 290ms	remaining: 1.26s
187:	learn: 6051.0670219	total: 291ms	remaining: 1.26s
188:	learn: 6047.7639483	total: 292ms	remaining: 1.25s
189:	learn: 6044.7657567	total: 294ms	remaining: 1.25s
190:	learn: 6036.6649174	total: 296ms	remaining: 1.25s
191:	learn: 6033.0007904	total: 297ms	remaining: 1.25s
192:	learn: 6027.9114531	total: 299ms	remaining: 1.25s
193:	learn: 6020.6161310	total: 300ms	remaining: 1.25s
194:	learn: 6016.5421273	total: 302ms	remaining: 1.24s
195:	learn: 6011.6541865	total: 303ms	remaining: 1.24s
196:	learn: 6007.9537343	total: 305ms	remaining: 1.24s
197:	learn: 6004.4856332	total: 306ms	remaining: 1.24s
198:	learn: 6000.2375287	total: 307ms	remaining: 1.24s
199:	learn: 5997.0704561	total: 309ms	remaining: 1.24s
200:	learn: 5992.1255220	total: 310ms	remaining: 1.23s
201:	learn: 5989.2898580	total: 312ms	remaining: 1.23s
202:	learn: 5985.6940444	total: 313ms	remaining: 1.23s
203:	learn: 5980.6824400	total: 315ms	remaining: 1.23s
204:	learn: 5976.1343627	total: 316ms	remaining: 1.23s
205:	learn: 5969.9170403	total: 318ms	remaining: 1.22s
206:	learn: 5965.2382709	total: 319ms	remaining: 1.22s
207:	learn: 5959.6540575	total: 321ms	remaining: 1.22s
208:	learn: 5957.6522329	total: 322ms	remaining: 1.22s
209:	learn: 5954.3163217	total: 324ms	remaining: 1.22s
210:	learn: 5947.2818705	total: 325ms	remaining: 1.22s
211:	learn: 5939.7437610	total: 326ms	remaining: 1.21s
212:	learn: 5936.3862877	total: 328ms	remaining: 1.21s
213:	learn: 5929.3942370	total: 329ms	remaining: 1.21s
214:	learn: 5923.2447767	total: 331ms	remaining: 1.21s
215:	learn: 5917.5195794	total: 332ms	remaining: 1.21s
216:	learn: 5914.0936259	total: 334ms	remaining: 1.2s
217:	learn: 5911.3265253	total: 335ms	remaining: 1.2s
218:	learn: 5904.6636197	total: 337ms	remaining: 1.2s
219:	learn: 5899.7972095	total: 339ms	remaining: 1.2s
220:	learn: 5893.8203429	total: 340ms	remaining: 1.2s
221:	learn: 5889.9264410	total: 342ms	remaining: 1.2s
222:	learn: 5884.0231765	total: 343ms	remaining: 1.2s
223:	learn: 5876.5755257	total: 345ms	remaining: 1.19s
224:	learn: 5870.5892018	total: 346ms	remaining: 1.19s
225:	learn: 5865.8911445	total: 347ms	remaining: 1.19s
226:	learn: 5862.3156802	total: 349ms	remaining: 1.19s
227:	learn: 5857.1847863	total: 350ms	remaining: 1.19s
228:	learn: 5854.1142203	total: 352ms	remaining: 1.19s
229:	learn: 5851.1955496	total: 353ms	remaining: 1.18s
230:	learn: 5844.1185801	total: 355ms	remaining: 1.18s
231:	learn: 5842.1647136	total: 356ms	remaining: 1.18s
232:	learn: 5837.8322557	total: 358ms	remaining: 1.18s
233:	learn: 5832.0436390	total: 359ms	remaining: 1.18s
234:	learn: 5830.6104013	total: 360ms	remaining: 1.17s
235:	learn: 5825.2003798	total: 362ms	remaining: 1.17s
236:	learn: 5821.4601385	total: 364ms	remaining: 1.17s
237:	learn: 5818.7672192	total: 365ms	remaining: 1.17s
238:	learn: 5815.0430730	total: 367ms	remaining: 1.17s
239:	learn: 5808.0179210	total: 368ms	remaining: 1.17s
240:	learn: 5804.7619908	total: 370ms	remaining: 1.17s
241:	learn: 5801.3034509	total: 371ms	remaining: 1.16s
242:	learn: 5798.6112003	total: 373ms	remaining: 1.16s
243:	learn: 5795.7918643	total: 375ms	remaining: 1.16s
244:	learn: 5792.5508517	total: 376ms	remaining: 1.16s
245:	learn: 5791.3602470	total: 377ms	remaining: 1.16s
246:	learn: 5788.0379123	total: 379ms	remaining: 1.16s
247:	learn: 5783.6888277	total: 381ms	remaining: 1.15s
248:	learn: 5781.0223493	total: 382ms	remaining: 1.15s
249:	learn: 5777.5523665	total: 384ms	remaining: 1.15s
250:	learn: 5775.3763173	total: 385ms	remaining: 1.15s
251:	learn: 5770.1661138	total: 387ms	remaining: 1.15s
252:	learn: 5767.4638449	total: 388ms	remaining: 1.15s
253:	learn: 5763.3944945	total: 390ms	remaining: 1.14s
254:	learn: 5759.9267792	total: 391ms	remaining: 1.14s
255:	learn: 5755.9657073	total: 392ms	remaining: 1.14s
256:	learn: 5750.6698330	total: 394ms	remaining: 1.14s
257:	learn: 5746.5699320	total: 396ms	remaining: 1.14s
258:	learn: 5743.0879305	total: 397ms	remaining: 1.14s
259:	learn: 5738.3882660	total: 398ms	remaining: 1.13s
260:	learn: 5733.7343986	total: 400ms	remaining: 1.13s
261:	learn: 5729.8857074	total: 401ms	remaining: 1.13s
262:	learn: 5724.8350153	total: 403ms	remaining: 1.13s
263:	learn: 5719.5331751	total: 404ms	remaining: 1.13s
264:	learn: 5714.1432335	total: 406ms	remaining: 1.13s
265:	learn: 5708.7807058	total: 407ms	remaining: 1.12s
266:	learn: 5704.6907641	total: 409ms	remaining: 1.12s
267:	learn: 5701.1561612	total: 410ms	remaining: 1.12s
268:	learn: 5698.5317221	total: 412ms	remaining: 1.12s
269:	learn: 5693.6406677	total: 413ms	remaining: 1.12s
270:	learn: 5688.1720379	total: 415ms	remaining: 1.11s
271:	learn: 5685.1765520	total: 416ms	remaining: 1.11s
272:	learn: 5682.5995895	total: 417ms	remaining: 1.11s
273:	learn: 5676.5983736	total: 419ms	remaining: 1.11s
274:	learn: 5672.5857908	total: 420ms	remaining: 1.11s
275:	learn: 5669.4610161	total: 422ms	remaining: 1.1s
276:	learn: 5665.4159083	total: 423ms	remaining: 1.1s
277:	learn: 5661.9106969	total: 424ms	remaining: 1.1s
278:	learn: 5659.4459630	total: 427ms	remaining: 1.1s
279:	learn: 5656.3852050	total: 428ms	remaining: 1.1s
280:	learn: 5652.7205711	total: 430ms	remaining: 1.1s
281:	learn: 5648.3960917	total: 432ms	remaining: 1.1s
282:	learn: 5644.7412842	total: 433ms	remaining: 1.1s
283:	learn: 5641.3163041	total: 435ms	remaining: 1.09s
284:	learn: 5636.7982089	total: 436ms	remaining: 1.09s
285:	learn: 5633.2948130	total: 437ms	remaining: 1.09s
286:	learn: 5628.6666418	total: 439ms	remaining: 1.09s
287:	learn: 5627.0571227	total: 440ms	remaining: 1.09s
288:	learn: 5622.9862766	total: 441ms	remaining: 1.09s
289:	learn: 5620.0901342	total: 443ms	remaining: 1.08s
290:	learn: 5617.3068122	total: 444ms	remaining: 1.08s
291:	learn: 5613.8983241	total: 446ms	remaining: 1.08s
292:	learn: 5610.1886975	total: 447ms	remaining: 1.08s
293:	learn: 5605.7148679	total: 448ms	remaining: 1.08s
294:	learn: 5601.3911198	total: 450ms	remaining: 1.07s
295:	learn: 5598.0360130	total: 451ms	remaining: 1.07s
296:	learn: 5594.3663657	total: 453ms	remaining: 1.07s
297:	learn: 5590.3986550	total: 454ms	remaining: 1.07s
298:	learn: 5584.9028362	total: 456ms	remaining: 1.07s
299:	learn: 5581.4947657	total: 457ms	remaining: 1.07s
300:	learn: 5576.8350451	total: 458ms	remaining: 1.06s
301:	learn: 5574.7699986	total: 460ms	remaining: 1.06s
302:	learn: 5570.0652606	total: 461ms	remaining: 1.06s
303:	learn: 5565.7266787	total: 463ms	remaining: 1.06s
304:	learn: 5561.1726786	total: 464ms	remaining: 1.06s
305:	learn: 5556.1310161	total: 465ms	remaining: 1.05s
306:	learn: 5553.1843811	total: 467ms	remaining: 1.05s
307:	learn: 5550.1761216	total: 468ms	remaining: 1.05s
308:	learn: 5546.1387638	total: 470ms	remaining: 1.05s
309:	learn: 5542.8001405	total: 471ms	remaining: 1.05s
310:	learn: 5539.1933246	total: 472ms	remaining: 1.05s
311:	learn: 5535.6549403	total: 474ms	remaining: 1.04s
312:	learn: 5530.9093120	total: 475ms	remaining: 1.04s
313:	learn: 5526.0603551	total: 477ms	remaining: 1.04s
314:	learn: 5523.1684303	total: 478ms	remaining: 1.04s
315:	learn: 5519.6966438	total: 479ms	remaining: 1.04s
316:	learn: 5517.2741358	total: 481ms	remaining: 1.03s
317:	learn: 5512.6251934	total: 482ms	remaining: 1.03s
318:	learn: 5511.3644177	total: 483ms	remaining: 1.03s
319:	learn: 5507.7357235	total: 485ms	remaining: 1.03s
320:	learn: 5505.1795841	total: 486ms	remaining: 1.03s
321:	learn: 5502.9641788	total: 488ms	remaining: 1.03s
322:	learn: 5500.5082672	total: 489ms	remaining: 1.02s
323:	learn: 5499.4152640	total: 490ms	remaining: 1.02s
324:	learn: 5495.1681645	total: 491ms	remaining: 1.02s
325:	learn: 5492.0987343	total: 493ms	remaining: 1.02s
326:	learn: 5489.4481224	total: 494ms	remaining: 1.02s
327:	learn: 5486.4980770	total: 496ms	remaining: 1.01s
328:	learn: 5484.6575251	total: 497ms	remaining: 1.01s
329:	learn: 5482.1775441	total: 499ms	remaining: 1.01s
330:	learn: 5479.9672011	total: 500ms	remaining: 1.01s
331:	learn: 5477.3707290	total: 501ms	remaining: 1.01s
332:	learn: 5473.3689947	total: 503ms	remaining: 1.01s
333:	learn: 5469.4301086	total: 504ms	remaining: 1s
334:	learn: 5464.7653139	total: 505ms	remaining: 1s
335:	learn: 5462.4088771	total: 507ms	remaining: 1s
336:	learn: 5457.9250869	total: 508ms	remaining: 1s
337:	learn: 5454.9461232	total: 510ms	remaining: 998ms
338:	learn: 5452.4334592	total: 511ms	remaining: 997ms
339:	learn: 5450.2657657	total: 512ms	remaining: 995ms
340:	learn: 5447.6145081	total: 514ms	remaining: 993ms
341:	learn: 5443.8897506	total: 515ms	remaining: 991ms
342:	learn: 5441.5141631	total: 517ms	remaining: 989ms
343:	learn: 5437.6022528	total: 518ms	remaining: 988ms
344:	learn: 5433.1507143	total: 519ms	remaining: 986ms
345:	learn: 5429.0615932	total: 521ms	remaining: 984ms
346:	learn: 5425.0539061	total: 522ms	remaining: 982ms
347:	learn: 5422.1404827	total: 523ms	remaining: 981ms
348:	learn: 5419.6483073	total: 525ms	remaining: 979ms
349:	learn: 5416.7410225	total: 526ms	remaining: 977ms
350:	learn: 5414.6379735	total: 528ms	remaining: 976ms
351:	learn: 5411.3124182	total: 529ms	remaining: 974ms
352:	learn: 5406.5432878	total: 531ms	remaining: 973ms
353:	learn: 5405.5010666	total: 532ms	remaining: 971ms
354:	learn: 5402.0913010	total: 534ms	remaining: 969ms
355:	learn: 5399.8654375	total: 535ms	remaining: 968ms
356:	learn: 5397.2768084	total: 536ms	remaining: 966ms

In [80]:
fig = go.Figure(data=[
    go.Bar(name='r2_train', x=df_models.Algorithm, y=df_models.r2_train),
    go.Bar(name='r2_test', x=df_models.Algorithm, y=df_models.r2_test)
])
fig.update_layout(template='plotly_dark', title='R2 for train and test', title_x=0.5)

#### We can see that Ensemble models working better than linear models which is quite usual as ensemble models mostly outperforms than linear models

#### In this case we will move forawrd with XGBoost as it is performing the best way possible

In [81]:
#import xgboost as xgb
#from sklearn.model_selection import train_test_split, cross_val_score
#from sklearn.metrics import r2_score

#best_model = XGBRegressor(reg_lambda=best_lambda,alpha=best_alpha,colsample_bytree=colsample_bytree,subsample=subsample,learning_rate=learning_rate,max_depth=max_depth,random_state=random_state,min_child_weight=min_child_weight,n_estimators=n_estimators)

#best_model.fit(X_train, y_train)

#eval_set = [(X_train, y_train), (X_test, y_test)]
#best_model.fit(X_train, y_train, eval_set=eval_set, early_stopping_rounds=100, verbose=False)

#y_pred_train = best_model.predict(X_train)
#y_pred_test = best_model.predict(X_test)

#train_r2 = r2_score(y_train, y_pred_train)
#test_r2 = r2_score(y_test, y_pred_test)

#print(f"Training R2 Score: {train_r2:.4f}")
#print(f"Testing R2 Score: {test_r2:.4f}")

<a id="1"></a> 
# <div style="text-align:center; border-radius:15px 50px; padding:7px; color:white; margin:0; font-size:110%; font-family:Pacifico; background-color:#0f7a7a; overflow:hidden"><b>Selecting best hyperparameter using Optuna </b></div>

In [25]:
from xgboost import XGBRegressor
import optuna
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score

def objective(trial):
    param = {
        #'tree_method':'gpu_hist',
        'lambda': trial.suggest_loguniform('lambda', 1e-3, 10.0),
        'alpha': trial.suggest_loguniform('alpha', 1e-3, 10.0),
        'colsample_bytree': trial.suggest_categorical('colsample_bytree', [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]),
        'subsample': trial.suggest_categorical('subsample', [0.4, 0.5, 0.6, 0.7, 0.8, 1.0]),
        'learning_rate': trial.suggest_categorical('learning_rate', [0.008, 0.01, 0.012, 0.014, 0.016, 0.018, 0.02]),
        'n_estimators': trial.suggest_int('n_estimators', 10, 1000),
        'max_depth': trial.suggest_categorical('max_depth', [5, 7, 9, 11, 13, 15, 17]),
        'random_state': trial.suggest_categorical('random_state', [2020]),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 300),
    }
    model = XGBRegressor(**param)
    model.fit(X_train, y_train, eval_set=[(X_test, y_test)], early_stopping_rounds=100, verbose=False)
    y_pred = model.predict(X_test)
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    return rmse

In [26]:
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=50)

[I 2024-07-14 08:39:16,191] A new study created in memory with name: no-name-5c3c1a53-d377-4230-ac49-25a6f3d8eebc
[I 2024-07-14 08:39:16,763] Trial 0 finished with value: 7677.472843079311 and parameters: {'lambda': 0.2926646056141708, 'alpha': 0.04131333995710903, 'colsample_bytree': 1.0, 'subsample': 0.4, 'learning_rate': 0.02, 'n_estimators': 546, 'max_depth': 11, 'random_state': 2020, 'min_child_weight': 150}. Best is trial 0 with value: 7677.472843079311.
[I 2024-07-14 08:39:17,211] Trial 1 finished with value: 7469.479762250803 and parameters: {'lambda': 0.6435216007603007, 'alpha': 6.352495616232941, 'colsample_bytree': 0.8, 'subsample': 0.7, 'learning_rate': 0.018, 'n_estimators': 309, 'max_depth': 11, 'random_state': 2020, 'min_child_weight': 119}. Best is trial 1 with value: 7469.479762250803.
[I 2024-07-14 08:39:17,301] Trial 2 finished with value: 11000.225298633413 and parameters: {'lambda': 0.01271080304277508, 'alpha': 0.04777266222136708, 'colsample_bytree': 0.5, 'subsample': 0.7, 'learning_rate': 0.014, 'n_estimators': 50, 'max_depth': 7, 'random_state': 2020, 'min_child_weight': 206}. Best is trial 1 with value: 7469.479762250803.
[I 2024-07-14 08:39:19,275] Trial 3 finished with value: 7192.6929400985555 and parameters: {'lambda': 0.18453453591874577, 'alpha': 2.642064735204213, 'colsample_bytree': 0.8, 'subsample': 1.0, 'learning_rate': 0.018, 'n_estimators': 865, 'max_depth': 11, 'random_state': 2020, 'min_child_weight': 112}. Best is trial 3 with value: 7192.6929400985555.
[I 2024-07-14 08:39:19,970] Trial 4 finished with value: 8194.266204422576 and parameters: {'lambda': 0.003593235516772611, 'alpha': 5.917111491594061, 'colsample_bytree': 1.0, 'subsample': 0.7, 'learning_rate': 0.008, 'n_estimators': 720, 'max_depth': 5, 'random_state': 2020, 'min_child_weight': 299}. Best is trial 3 with value: 7192.6929400985555.
[I 2024-07-14 08:39:20,542] Trial 5 finished with value: 7864.475722707221 and parameters: {'lambda': 7.457401056620626, 'alpha': 0.12302885453890619, 'colsample_bytree': 0.5, 'subsample': 0.5, 'learning_rate': 0.014, 'n_estimators': 609, 'max_depth': 11, 'random_state': 2020, 'min_child_weight': 188}. Best is trial 3 with value: 7192.6929400985555.
[I 2024-07-14 08:39:20,936] Trial 6 finished with value: 7948.636773995998 and parameters: {'lambda': 0.016486869709963974, 'alpha': 0.004136012508420796, 'colsample_bytree': 0.4, 'subsample': 0.8, 'learning_rate': 0.008, 'n_estimators': 241, 'max_depth': 13, 'random_state': 2020, 'min_child_weight': 33}. Best is trial 3 with value: 7192.6929400985555.
[I 2024-07-14 08:39:21,397] Trial 7 finished with value: 7769.055036309303 and parameters: {'lambda': 0.008907900249915692, 'alpha': 0.0012624982842432402, 'colsample_bytree': 0.8, 'subsample': 0.4, 'learning_rate': 0.014, 'n_estimators': 460, 'max_depth': 17, 'random_state': 2020, 'min_child_weight': 126}. Best is trial 3 with value: 7192.6929400985555.
[I 2024-07-14 08:39:21,993] Trial 8 finished with value: 7527.775761080419 and parameters: {'lambda': 0.08129091696562801, 'alpha': 4.154785687577161, 'colsample_bytree': 1.0, 'subsample': 0.4, 'learning_rate': 0.008, 'n_estimators': 496, 'max_depth': 9, 'random_state': 2020, 'min_child_weight': 70}. Best is trial 3 with value: 7192.6929400985555.
[I 2024-07-14 08:39:22,640] Trial 9 finished with value: 7254.610992819643 and parameters: {'lambda': 0.015468839017407405, 'alpha': 0.02564463236261849, 'colsample_bytree': 0.5, 'subsample': 1.0, 'learning_rate': 0.014, 'n_estimators': 473, 'max_depth': 17, 'random_state': 2020, 'min_child_weight': 88}. Best is trial 3 with value: 7192.6929400985555.
[I 2024-07-14 08:39:23,518] Trial 10 finished with value: 6908.517124108219 and parameters: {'lambda': 3.367052823996112, 'alpha': 0.8039198621635125, 'colsample_bytree': 0.9, 'subsample': 0.6, 'learning_rate': 0.018, 'n_estimators': 983, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 11}. Best is trial 10 with value: 6908.517124108219.
[I 2024-07-14 08:39:24,687] Trial 11 finished with value: 6916.238404573405 and parameters: {'lambda': 6.503486215427664, 'alpha': 0.6958975361845251, 'colsample_bytree': 0.9, 'subsample': 0.6, 'learning_rate': 0.018, 'n_estimators': 949, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 6}. Best is trial 10 with value: 6908.517124108219.
[I 2024-07-14 08:39:27,273] Trial 12 finished with value: 6894.779394772452 and parameters: {'lambda': 7.7456840263756375, 'alpha': 0.4451220180254984, 'colsample_bytree': 0.9, 'subsample': 0.6, 'learning_rate': 0.012, 'n_estimators': 961, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 2}. Best is trial 12 with value: 6894.779394772452.
[I 2024-07-14 08:39:28,873] Trial 13 finished with value: 7046.8917330637505 and parameters: {'lambda': 1.7880384873974933, 'alpha': 0.4191519771219565, 'colsample_bytree': 0.9, 'subsample': 0.6, 'learning_rate': 0.012, 'n_estimators': 994, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 40}. Best is trial 12 with value: 6894.779394772452.
[I 2024-07-14 08:39:29,857] Trial 14 finished with value: 6881.189799592934 and parameters: {'lambda': 1.9730158968528881, 'alpha': 0.7428469010511224, 'colsample_bytree': 0.9, 'subsample': 0.6, 'learning_rate': 0.016, 'n_estimators': 805, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 7}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:30,986] Trial 15 finished with value: 7172.475251200087 and parameters: {'lambda': 1.2394242242573774, 'alpha': 0.19665619504798235, 'colsample_bytree': 0.6, 'subsample': 0.6, 'learning_rate': 0.016, 'n_estimators': 801, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 61}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:31,665] Trial 16 finished with value: 8530.34263490701 and parameters: {'lambda': 8.255408374450212, 'alpha': 1.4199024172099644, 'colsample_bytree': 0.7, 'subsample': 0.6, 'learning_rate': 0.016, 'n_estimators': 756, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 289}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:32,619] Trial 17 finished with value: 7042.175650763307 and parameters: {'lambda': 0.07094847119896093, 'alpha': 0.357373891874202, 'colsample_bytree': 0.3, 'subsample': 0.8, 'learning_rate': 0.01, 'n_estimators': 675, 'max_depth': 7, 'random_state': 2020, 'min_child_weight': 1}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:33,405] Trial 18 finished with value: 8505.76367948054 and parameters: {'lambda': 0.7325250711009406, 'alpha': 0.015114624691572369, 'colsample_bytree': 0.9, 'subsample': 0.5, 'learning_rate': 0.012, 'n_estimators': 868, 'max_depth': 5, 'random_state': 2020, 'min_child_weight': 237}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:34,745] Trial 19 finished with value: 7059.77144797716 and parameters: {'lambda': 2.667621854591529, 'alpha': 1.6845483543911755, 'colsample_bytree': 0.9, 'subsample': 0.6, 'learning_rate': 0.012, 'n_estimators': 857, 'max_depth': 13, 'random_state': 2020, 'min_child_weight': 41}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:36,910] Trial 20 finished with value: 7266.140022278967 and parameters: {'lambda': 0.6059740945871298, 'alpha': 0.22036523849390338, 'colsample_bytree': 0.7, 'subsample': 0.6, 'learning_rate': 0.016, 'n_estimators': 681, 'max_depth': 9, 'random_state': 2020, 'min_child_weight': 85}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:37,894] Trial 21 finished with value: 6921.527668310288 and parameters: {'lambda': 2.9355263585194376, 'alpha': 0.8800951690158149, 'colsample_bytree': 0.9, 'subsample': 0.6, 'learning_rate': 0.02, 'n_estimators': 999, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 14}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:39,353] Trial 22 finished with value: 7017.369637259582 and parameters: {'lambda': 3.2150409496422454, 'alpha': 0.6175563586826455, 'colsample_bytree': 0.9, 'subsample': 0.6, 'learning_rate': 0.01, 'n_estimators': 909, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 29}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:40,538] Trial 23 finished with value: 7119.4082791514975 and parameters: {'lambda': 4.756630380737455, 'alpha': 0.08706255507041655, 'colsample_bytree': 0.9, 'subsample': 0.6, 'learning_rate': 0.018, 'n_estimators': 817, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 57}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:42,189] Trial 24 finished with value: 6964.998411967061 and parameters: {'lambda': 1.252407443433429, 'alpha': 1.4573426026692113, 'colsample_bytree': 0.4, 'subsample': 0.6, 'learning_rate': 0.016, 'n_estimators': 928, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 4}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:43,108] Trial 25 finished with value: 7417.425348733012 and parameters: {'lambda': 0.2924855041842338, 'alpha': 2.68404498858124, 'colsample_bytree': 0.3, 'subsample': 0.6, 'learning_rate': 0.012, 'n_estimators': 777, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 89}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:44,239] Trial 26 finished with value: 7004.194961001243 and parameters: {'lambda': 0.0012023154357652906, 'alpha': 0.20821559687645724, 'colsample_bytree': 0.6, 'subsample': 1.0, 'learning_rate': 0.012, 'n_estimators': 928, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 33}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:45,658] Trial 27 finished with value: 7104.627567706146 and parameters: {'lambda': 4.091436145514986, 'alpha': 0.3818704765205522, 'colsample_bytree': 0.9, 'subsample': 0.5, 'learning_rate': 0.018, 'n_estimators': 998, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 52}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:46,376] Trial 28 finished with value: 6985.942057001404 and parameters: {'lambda': 9.992362289240726, 'alpha': 1.037038662510565, 'colsample_bytree': 0.9, 'subsample': 0.8, 'learning_rate': 0.016, 'n_estimators': 619, 'max_depth': 5, 'random_state': 2020, 'min_child_weight': 20}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:46,926] Trial 29 finished with value: 7918.825136307974 and parameters: {'lambda': 0.0423406048649509, 'alpha': 0.07586105273958864, 'colsample_bytree': 0.9, 'subsample': 0.4, 'learning_rate': 0.02, 'n_estimators': 338, 'max_depth': 17, 'random_state': 2020, 'min_child_weight': 156}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:47,931] Trial 30 finished with value: 7542.916067169848 and parameters: {'lambda': 0.2733631975085468, 'alpha': 8.892700898494907, 'colsample_bytree': 0.9, 'subsample': 0.6, 'learning_rate': 0.01, 'n_estimators': 843, 'max_depth': 13, 'random_state': 2020, 'min_child_weight': 141}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:48,987] Trial 31 finished with value: 6920.76076163842 and parameters: {'lambda': 5.25110509866749, 'alpha': 0.6695080536481957, 'colsample_bytree': 0.9, 'subsample': 0.6, 'learning_rate': 0.018, 'n_estimators': 955, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 8}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:49,853] Trial 32 finished with value: 6974.101935885508 and parameters: {'lambda': 1.732597295260767, 'alpha': 0.5175779354792935, 'colsample_bytree': 0.9, 'subsample': 0.6, 'learning_rate': 0.018, 'n_estimators': 907, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 23}. Best is trial 14 with value: 6881.189799592934.
[I 2024-07-14 08:39:50,781] Trial 33 finished with value: 6790.751631126518 and parameters: {'lambda': 0.5486948817066843, 'alpha': 2.5389310538514476, 'colsample_bytree': 0.9, 'subsample': 0.7, 'learning_rate': 0.018, 'n_estimators': 944, 'max_depth': 7, 'random_state': 2020, 'min_child_weight': 2}. Best is trial 33 with value: 6790.751631126518.
[I 2024-07-14 08:39:51,806] Trial 34 finished with value: 7124.230886617906 and parameters: {'lambda': 0.6490749224262454, 'alpha': 2.560209837161155, 'colsample_bytree': 0.7, 'subsample': 0.7, 'learning_rate': 0.018, 'n_estimators': 877, 'max_depth': 7, 'random_state': 2020, 'min_child_weight': 74}. Best is trial 33 with value: 6790.751631126518.
[I 2024-07-14 08:39:52,654] Trial 35 finished with value: 7059.176114706066 and parameters: {'lambda': 0.15222449285476328, 'alpha': 2.862518253715429, 'colsample_bytree': 1.0, 'subsample': 0.7, 'learning_rate': 0.018, 'n_estimators': 744, 'max_depth': 7, 'random_state': 2020, 'min_child_weight': 44}. Best is trial 33 with value: 6790.751631126518.
[I 2024-07-14 08:39:52,890] Trial 36 finished with value: 7137.790783896248 and parameters: {'lambda': 0.43031569042566215, 'alpha': 5.965535173817847, 'colsample_bytree': 0.8, 'subsample': 0.7, 'learning_rate': 0.02, 'n_estimators': 137, 'max_depth': 7, 'random_state': 2020, 'min_child_weight': 19}. Best is trial 33 with value: 6790.751631126518.
[I 2024-07-14 08:39:53,493] Trial 37 finished with value: 7625.157047852164 and parameters: {'lambda': 1.1116342214910682, 'alpha': 0.2825437025807097, 'colsample_bytree': 0.4, 'subsample': 0.7, 'learning_rate': 0.018, 'n_estimators': 549, 'max_depth': 11, 'random_state': 2020, 'min_child_weight': 175}. Best is trial 33 with value: 6790.751631126518.
[I 2024-07-14 08:39:54,295] Trial 38 finished with value: 7728.822563006059 and parameters: {'lambda': 2.0576656218584906, 'alpha': 1.0766794017143342, 'colsample_bytree': 0.5, 'subsample': 0.7, 'learning_rate': 0.012, 'n_estimators': 809, 'max_depth': 7, 'random_state': 2020, 'min_child_weight': 214}. Best is trial 33 with value: 6790.751631126518.
[I 2024-07-14 08:39:55,209] Trial 39 finished with value: 7321.026085157243 and parameters: {'lambda': 0.8707910922281519, 'alpha': 0.13186690087991657, 'colsample_bytree': 0.6, 'subsample': 1.0, 'learning_rate': 0.008, 'n_estimators': 703, 'max_depth': 9, 'random_state': 2020, 'min_child_weight': 97}. Best is trial 33 with value: 6790.751631126518.
[I 2024-07-14 08:39:55,597] Trial 40 finished with value: 7804.9787719537235 and parameters: {'lambda': 0.47370196306897994, 'alpha': 4.246089030424294, 'colsample_bytree': 0.3, 'subsample': 0.5, 'learning_rate': 0.016, 'n_estimators': 342, 'max_depth': 11, 'random_state': 2020, 'min_child_weight': 108}. Best is trial 33 with value: 6790.751631126518.
[I 2024-07-14 08:39:57,879] Trial 41 finished with value: 6897.730965355937 and parameters: {'lambda': 5.835886137287302, 'alpha': 0.7453803742422255, 'colsample_bytree': 0.9, 'subsample': 0.6, 'learning_rate': 0.018, 'n_estimators': 954, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 1}. Best is trial 33 with value: 6790.751631126518.
[I 2024-07-14 08:39:58,723] Trial 42 finished with value: 6992.2690973506815 and parameters: {'lambda': 4.912992972628033, 'alpha': 2.4043414324058396, 'colsample_bytree': 0.9, 'subsample': 0.6, 'learning_rate': 0.018, 'n_estimators': 962, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 22}. Best is trial 33 with value: 6790.751631126518.
[I 2024-07-14 08:39:59,927] Trial 43 finished with value: 7124.024152455254 and parameters: {'lambda': 2.029557141708835, 'alpha': 1.7606127816841348, 'colsample_bytree': 0.9, 'subsample': 0.4, 'learning_rate': 0.018, 'n_estimators': 893, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 48}. Best is trial 33 with value: 6790.751631126518.
[I 2024-07-14 08:40:03,637] Trial 44 finished with value: 6961.081469970227 and parameters: {'lambda': 7.081061137831018, 'alpha': 0.9044774164130073, 'colsample_bytree': 0.8, 'subsample': 0.8, 'learning_rate': 0.014, 'n_estimators': 966, 'max_depth': 17, 'random_state': 2020, 'min_child_weight': 1}. Best is trial 33 with value: 6790.751631126518.
[I 2024-07-14 08:40:04,518] Trial 45 finished with value: 7162.064024152732 and parameters: {'lambda': 3.518948891360646, 'alpha': 0.050140593114316, 'colsample_bytree': 0.9, 'subsample': 0.6, 'learning_rate': 0.018, 'n_estimators': 846, 'max_depth': 5, 'random_state': 2020, 'min_child_weight': 64}. Best is trial 33 with value: 6790.751631126518.
[I 2024-07-14 08:40:05,709] Trial 46 finished with value: 7035.432542817594 and parameters: {'lambda': 1.5474858439236292, 'alpha': 0.1415501981711217, 'colsample_bytree': 0.9, 'subsample': 0.7, 'learning_rate': 0.008, 'n_estimators': 936, 'max_depth': 7, 'random_state': 2020, 'min_child_weight': 33}. Best is trial 33 with value: 6790.751631126518.
[I 2024-07-14 08:40:06,693] Trial 47 finished with value: 6921.385908496391 and parameters: {'lambda': 9.40522120512969, 'alpha': 4.109626408977044, 'colsample_bytree': 1.0, 'subsample': 0.6, 'learning_rate': 0.018, 'n_estimators': 893, 'max_depth': 15, 'random_state': 2020, 'min_child_weight': 14}. Best is trial 33 with value: 6790.751631126518.
[I 2024-07-14 08:40:06,909] Trial 48 finished with value: 10778.36064343729 and parameters: {'lambda': 2.6428636816045765, 'alpha': 0.4686412741861488, 'colsample_bytree': 0.5, 'subsample': 1.0, 'learning_rate': 0.014, 'n_estimators': 40, 'max_depth': 13, 'random_state': 2020, 'min_child_weight': 1}. Best is trial 33 with value: 6790.751631126518.
[I 2024-07-14 08:40:09,449] Trial 49 finished with value: 7015.142515141147 and parameters: {'lambda': 6.335743348789765, 'alpha': 0.001405438607696375, 'colsample_bytree': 0.9, 'subsample': 0.6, 'learning_rate': 0.012, 'n_estimators': 800, 'max_depth': 9, 'random_state': 2020, 'min_child_weight': 29}. Best is trial 33 with value: 6790.751631126518.

In [27]:
print('Best parameters:', study.best_params)
print('Best RMSE:', study.best_value)

Best parameters: {'lambda': 0.5486948817066843, 'alpha': 2.5389310538514476, 'colsample_bytree': 0.9, 'subsample': 0.7, 'learning_rate': 0.018, 'n_estimators': 944, 'max_depth': 7, 'random_state': 2020, 'min_child_weight': 2}
Best RMSE: 6790.751631126518

In [28]:
#plotting the optimization history of the study
optuna.visualization.plot_optimization_history(study)

In [29]:
#studying the relationship between each value of hyperparameter through this plot
optuna.visualization.plot_parallel_coordinate(study)

In [30]:
# now we plot the accuracy of each hyperparameter for each trial
optuna.visualization.plot_slice(study)

In [31]:
#plotting the accuracy surface for the hyperparameter involved in the xgb
optuna.visualization.plot_contour(study, params=['alpha',
                            'lambda',
                            'subsample',
                            'learning_rate','subsample','n_estimators'])

In [32]:
#Now we look at the role of each parameter in this process
optuna.visualization.plot_param_importances(study)

In [33]:
best_params = study.best_params
best_score = study.best_value
print(f"Best Hyperparameters: {best_params}")
print(f"Best Accuracy: {best_score:.3f}")

Best Hyperparameters: {'lambda': 0.5486948817066843, 'alpha': 2.5389310538514476, 'colsample_bytree': 0.9, 'subsample': 0.7, 'learning_rate': 0.018, 'n_estimators': 944, 'max_depth': 7, 'random_state': 2020, 'min_child_weight': 2}
Best Accuracy: 6790.752

In [34]:
#fetching the best values
best_lambda = best_params['lambda']
best_alpha = best_params['alpha']
colsample_bytree = best_params['colsample_bytree']
subsample = best_params['subsample']
learning_rate = best_params['learning_rate']
max_depth = best_params['max_depth']
random_state = best_params['random_state']
min_child_weight = best_params['min_child_weight']
n_estimators=best_params['n_estimators']


best_model = XGBRegressor(
    reg_lambda=best_lambda,
    alpha=best_alpha,
    colsample_bytree=colsample_bytree,
    subsample=subsample,
    learning_rate=learning_rate,
    max_depth=max_depth,
    random_state=random_state,
    min_child_weight=min_child_weight,
    n_estimators=n_estimators
)

# Fitting the model on the training data
best_model.fit(X_train, y_train)

XGBRegressor(alpha=2.5389310538514476, base_score=None, booster=None,
             callbacks=None, colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.9, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.018, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=7, max_leaves=None,
             min_child_weight=2, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=944, n_jobs=None,
             num_parallel_tree=None, ...)

In [35]:
print(f'Best model result in Test: {r2_score(y_test, best_model.predict(X_test))}')
print(f'Best model result in Train: {r2_score(y_train, best_model.predict(X_train))}')

Best model result in Test: 0.7710212133830716
Best model result in Train: 0.973815412313862

Using optuna we can clearly see it is overfitting so let us try with Bagging models and fingers crossed lets see if it works out

<a id="1"></a> 
# <div style="text-align:center; border-radius:15px 50px; padding:7px; color:white; margin:0; font-size:110%; font-family:Pacifico; background-color:#0f7a7a; overflow:hidden"><b>Bagging Ensemble</b></div>

In [36]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor


n_samples = X_train_scaled.shape[0]
n_features = X_train_scaled.shape[1]

params = {'base_estimator': [None, LinearRegression(), KNeighborsRegressor(), DecisionTreeRegressor(),GradientBoostingRegressor()],
          'n_estimators': [20,50,100],
          'max_samples': [0.5,1.0],
          'max_features': [0.5,1.0],
          'bootstrap': [True, False],
          'bootstrap_features': [True, False]}

bagging_regressor_grid = GridSearchCV(BaggingRegressor(random_state=1, n_jobs=-1), param_grid=params, cv=3, n_jobs=-1, verbose=1)
bagging_regressor_grid.fit(X_train_scaled, y_train)

Fitting 3 folds for each of 240 candidates, totalling 720 fits

/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

GridSearchCV(cv=3, estimator=BaggingRegressor(n_jobs=-1, random_state=1),
             n_jobs=-1,
             param_grid={'base_estimator': [None, LinearRegression(),
                                            KNeighborsRegressor(),
                                            DecisionTreeRegressor(),
                                            GradientBoostingRegressor()],
                         'bootstrap': [True, False],
                         'bootstrap_features': [True, False],
                         'max_features': [0.5, 1.0], 'max_samples': [0.5, 1.0],
                         'n_estimators': [20, 50, 100]},
             verbose=1)

In [37]:
print('Train R^2 Score : %.3f'%bagging_regressor_grid.best_estimator_.score(X_train_scaled, y_train))
print('Test R^2 Score : %.3f'%bagging_regressor_grid.best_estimator_.score(X_test_scaled, y_test))
print('Best R^2 Score Through Grid Search : %.3f'%bagging_regressor_grid.best_score_)
print('Best Parameters : ',bagging_regressor_grid.best_params_)

Train R^2 Score : 0.789
Test R^2 Score : 0.749
Best R^2 Score Through Grid Search : 0.735
Best Parameters :  {'base_estimator': GradientBoostingRegressor(), 'bootstrap': False, 'bootstrap_features': False, 'max_features': 1.0, 'max_samples': 0.5, 'n_estimators': 50}

In [38]:
from sklearn.ensemble import BaggingRegressor
bag_regressor = BaggingRegressor(
    random_state=1,
    n_jobs=-1,
    base_estimator=GradientBoostingRegressor(),
    bootstrap=False,
    bootstrap_features=False,
    max_features=1.0,
    max_samples=0.5,
    n_estimators=50
)
bag_regressor.fit(X_train_scaled, y_train)
Y_preds = bag_regressor.predict(X_test_scaled)
print('Training Coefficient of R^2 : %.3f' % bag_regressor.score(X_train_scaled, y_train))
print('Test Coefficient of R^2 : %.3f' % bag_regressor.score(X_test_scaled, y_test))

Training Coefficient of R^2 : 0.789
Test Coefficient of R^2 : 0.749

#### Ah finally a descent result :) so thats all for this notebook :)